### ISSUE TITLE
Conflict with set 'li' and 'active-class'

### ISSUE THREAD

**Issue by ZoIcHi** [davicotico/PHP-Quick-Menu#1]
hi, first of all congratulations for the excellent script.

unfortunately I noticed a bug ...

if in boostrapmenu.php set the parameter 'li', with a class, the class 'active-class' is not applied.

I think the problem is that there is no correct merge between,

`'li', array('class'=>'nav-item')` in BootstrapMenu.php
and
`$this->set('active-class', array('class' => $this->activeClass));` in QuickMenu.php row #63

Regards

**Comment by davicotico** [comment]
@ZoIcHi thanks for report the bug.
My apologies for the late response.
You are right, there is a conflict and the script is generating a duplicate class attribute instead of adding the class:
`<li class="test-classitem" class="active">...</li>`
I am gonna to fix the bug and then release the version 1.0.1
Thanks again.

**Comment by davicotico** [comment]
PHP QuickMenu 1.0.1 is available.
https://github.com/davicotico/PHP-Quick-Menu/releases
